apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  annotations:
    github.com/project-slug: alfredglz/backstage-test
    backstage.io/managed-by-location: url:http://github.com/alfredglz/backstage-test/blob/main/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
  links:
  - url: .
spec:
  type: other
  lifecycle: experimental
  owner: gru
